---
layout: issue
title: "Exception thrown in destructor"
id: ZF-10498
---

ZF-10498: Exception thrown in destructor
----------------------------------------

 Issue Type: Bug Created: 2010-09-27T01:02:28.000+0000 Last Updated: 2011-01-16T03:03:45.000+0000 Status: Open Fix version(s): 
 Reporter:  Marcin Kowalski (mkowalski)  Assignee:  Eddo Rotman (karnaf)  Tags: - Zend\_Log
 
 Related issues: 
 Attachments: 
### Description

Zend\_Log's \_\_destruct method may throw exceptions in case any writer's shutdown() does. According to PHP's manual, it is a bug to throw exceptions inside destructors.

 

 

### Comments

Posted by Beno√Æt Durand (intiilapa) on 2011-01-16T03:03:45.000+0000

No writer can throw an exception in the shutdown method. The mail writer has try/catch, and others can not throw an exception.

 

 