---
layout: issue
title: "Zend_Db (PDO_MYSQL) Exception does not contain &quot;code&quot;"
id: ZF-1137
---

ZF-1137: Zend\_Db (PDO\_MYSQL) Exception does not contain "code"
----------------------------------------------------------------

 Issue Type: Bug Created: 2007-03-26T08:13:26.000+0000 Last Updated: 2007-07-05T14:43:59.000+0000 Status: Resolved Fix version(s): - 0.9.2 (06/Apr/07)
 
 Reporter:  Till Klampaeckel (till)  Assignee:  Bill Karwin (bkarwin)  Tags: - Zend\_Db
 
 Related issues: 
 Attachments: 
### Description

We are distributing DB changes with SQL files which we loaded at the first request when someone logs into the application.

In order to catch the exception ("SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'foo"), I checked with $e->getCode() inside the catch blog. Until the release of 0.9.1 this was working. With 0.9.1 getCode() returns 0 (int).

 
    <pre class="highlight">
        try
        {
            $sql = "ALTER %s.TABLE AND SO ON...";
            $sql = sprintf($sql, $f->filter($session->db));
            $db->query($sql);
        }
        catch(Exception $e)
        {
            //Zend_Debug::dump(get_class_methods($e));
            //Zend_Debug::dump($e->getCode());
            if ($e->getCode() != '42S21')
            {
                throw $e;  
            }
        }


(I know, I should have probably used the constant instead of matching '42S21', but it doesn't work anyway - anymore.)

 

 

### Comments

Posted by Bill Karwin (bkarwin) on 2007-03-26T08:57:31.000+0000

Fixed in revision 4236.

The resolution of ZF-1031 made PDO drivers return a Zend\_Db\_Adapter\_Exception instead of a PDOException. The former includes a reference to the latter, accessible through getChainedException().

The fix for this issue makes Zend\_Db\_Adapter\_Exception set its own code to that of the chained Exception, if one has been passed.

You can use the following workaround immediately:

 
    <pre class="highlight">
    catch (Zend_Db_Adapter_Exception $e) {
        if ($e->getChainedException()->getCode() ...) {
            ...
        }
    }


Or you can update to revision 4236 and you won't have to change your code.

 

 