---
layout: issue
title: "Zend_Ldap_Collection::toArray throws exception instead of returning array"
id: ZF-11946
---

ZF-11946: Zend\_Ldap\_Collection::toArray throws exception instead of returning array
-------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2011-12-17T10:06:35.000+0000 Last Updated: 2012-01-21T15:24:32.000+0000 Status: Resolved Fix version(s): - 1.11.12 (22/Jun/12)
- 1.12.0 (27/Aug/12)
- Next Major Release ()
 
 Reporter:  Igor Orekhov (igvalor)  Assignee:  Stefan Gehrig (sgehrig)  Tags: - Zend\_Ldap
 
 Related issues: 
 Attachments: 
### Description

When I try to perform Zend\_Ldap::search(...)->toArray(), an exception is thrown:

Message: 0x54 (Decoding error): getting next entry (0x54 (Decoding error))

The actual problem is in Zend\_Ldap\_Collection\_Iterator\_Default::next(), which internally calls PHP's ldap\_next\_entry(). Upon reaching the end of the found entries, which is indicated by returning FALSE by ldap\_next\_entry(), Zend\_Ldap\_Collection\_Iterator\_Default::next() throws the exception instead of returning.

 

 

### Comments

Posted by Stefan Gehrig (sgehrig) on 2012-01-21T15:24:32.000+0000

Could not really reproduce this issue but added a second safe-guard against an exception on an empty search result

 

 