---
layout: issue
title: "calling prepare on a mysqli object fails on internal prepare method"
id: ZF-10808
---

ZF-10808: calling prepare on a mysqli object fails on internal prepare method
-----------------------------------------------------------------------------

 Issue Type: Bug Created: 2010-12-10T07:09:01.000+0000 Last Updated: 2011-04-01T19:46:22.000+0000 Status: Resolved Fix version(s): 
 Reporter:  Jonathan Reid Kushner (jkushner1019)  Assignee:  Ralph Schindler (ralph)  Tags: - Zend\_Db
 
 Related issues: 
 Attachments: 
### Description

On line 70 of Zend\_Db\_Statement\_Mysqli, there is a call made to $this->\_stmt = $mysqli->prepare($sql); This call failed every time a sql query was being made because I don't believe you should be preparing the sql query from the mysqli object, and thus the statement object was never returned. this issue was a primary blocker from us using Zend\_Db again.

 

 

### Comments

Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T11:19:35.000+0000

Could you please provide an example illustrating the problem you are encountering and any resulting error message(s)? Thanks!

 

 