---
layout: issue
title: "Unit test failure, probably bug in unit test."
id: ZF-732
---

ZF-732: Unit test failure, probably bug in unit test.
-----------------------------------------------------

 Issue Type: Bug Created: 2007-01-09T11:32:31.000+0000 Last Updated: 2007-07-05T14:43:39.000+0000 Status: Resolved Fix version(s): - 0.7.0 (18/Jan/07)
 
 Reporter:  Gavin (gavin)  Assignee:  Thomas Weidner (thomas)  Tags: - Zend\_Date
 
 Related issues: 
 Attachments: 
### Description

phpunit Zend\_DateTest.php X-Powered-By: PHP/5.1.6 Content-type: text/html

PHPUnit 3.0.0 by Sebastian Bergmann.

....................F.................... ....E...........

Time: 00:05

There was 1 error:

1) testAddArpa(Zend\_DateTest) Zend\_Date\_Exception: invalid date (Fri, 05 Jan 07 03:35:53 GMT) operand, RFC 822 date format expected /var/www/html/zftrunk/incubator/library/Zend/Date.php:1010 /var/www/html/zftrunk/incubator/library/Zend/Date.php:2972 /var/www/html/zftrunk/incubator/library/Zend/Date.php:2678 /var/www/html/zftrunk/incubator/library/Zend/Date.php:2700 /var/www/html/zftrunk/incubator/tests/Zend/DateTest.php:3256 /usr/local/php5/bin/phpunit:40 There was 1 failure:

1) testAdd(Zend\_DateTest) <<<<<<<<<<<<<<< looks like unit test is wrong, and not code Failed asserting that

 

 

### Comments

Posted by Thomas Weidner (thomas) on 2007-01-09T12:42:02.000+0000

I will check this, but also to mention : With SVN 2659 no failure did show up, so anywhen after that commit the error was included.

 

 

Posted by Gavin (gavin) on 2007-01-09T12:54:29.000+0000

$ svn update At revision 2671.

$ php -v PHP 5.1.6 (cgi-fcgi) (built: Oct 24 2006 19:38:28) Copyright (c) 1997-2006 The PHP Group Zend Engine v2.1.0, Copyright (c) 1998-2006 Zend Technologies

$ uname -a Linux sandbox.zend.com 2.6.9-34.EL #1 Fri Feb 24 16:44:51 EST 2006 i686 i686 i386 GNU/Linux

Do you have an account on [http://framework.zend.com/wiki/display/â€¦](http://framework.zend.com/wiki/display/ZFDEV/Sandbox) ?

 
    <pre class="highlight">
            $retour = $date->set(1234567890);
            $this->assertSame((string)$retour,'1234567890');
            $this->assertSame((string)$date->add(10),'1234567900');
            $this->assertSame((string)$date->add(-10),'1234567890');
            $this->assertSame((string)$date->add(1),'1234567890');


I do not see an intuitive reason why the last line of code would result add() yielding '1234567890' instead of '1234567891'.

 

 

Posted by Gavin (gavin) on 2007-01-09T12:55:19.000+0000

The code above is from the unit test public function testAdd() in Zend/DateTest.php

 

 

Posted by Gavin (gavin) on 2007-01-09T12:57:16.000+0000

I suspect one of the recent commits fixed a bug, and now the unit test is failing, because the unit test was buggy.

 

 

Posted by Thomas Weidner (thomas) on 2007-01-09T13:00:14.000+0000

Within SVN 2670 the following lines were changed by to throw an failure:

- $this->assertSame($date->add(0),'1234567890');
- $this->assertSame((string)$date->add(1),'1234567890');

I reverted the changed 1 to 0 as the addition of positive values is already checked with add(10).

Fixed with SVN 2672

 

 

Posted by Gavin (gavin) on 2007-01-09T13:10:02.000+0000

yup .. looks like that was my fault .. not sure how that 0 got changed to a 1 .. thanks :)

 

 

Posted by Thomas Weidner (thomas) on 2007-01-09T13:10:51.000+0000

Related to you question before:

No I dont have an account on the sandbox... But I have my own testserver and I always test before I commit changed functions.

Related to reason:

The initial reason was to check if add(0) behaves correct. You just changed the test and forgot also to change the result... only a typo.

 

 

Posted by Gavin (gavin) on 2007-01-09T13:23:38.000+0000

I remember now .. I was running a quick test while we were chatting yesterday. I forgot to undo the change. Then there was a separate issue relating to needing the (string) cast in order for the unit tests to work correctly, when bcmath is not enabled. So I expected that line of code to show up in "svn diff", but forgot to put the 1 back to 0. Then I thought somehow the unit test was wrong, so I committed the code anyway, even though the code didn't pass that unit test. I was right .. unit test was wrong .. but I made it wrong .. lol .. oops.

 

 