---
layout: issue
title: "Setting up a Cache with automatic_serialization will not throw an exception but fail"
id: ZF-7720
---

ZF-7720: Setting up a Cache with automatic\_serialization will not throw an exception but fail
----------------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2009-08-29T04:33:03.000+0000 Last Updated: 2009-08-29T11:55:07.000+0000 Status: Resolved Fix version(s): - 1.9.3 (22/Sep/09)
 
 Reporter:  Saman Darougheh (excuvator)  Assignee:  Thomas Weidner (thomas)  Tags: - Zend\_Locale
 
 Related issues: 
 Attachments: 
### Description

first of all, it was impossible for me to find into which folder Zend\_Locale's default cache will try to write, that was why I set up my default cache for Zend\_Locale. Unfortunatelly, that one had array('automatic\_serialization' => true); what returned in a mess (<http://pastie.org/598710>) instead of throwing some exception.

 

 

### Comments

Posted by Thomas Weidner (thomas) on 2009-08-29T07:48:34.000+0000

You should always look if an actual release fixed the error.

1.8.0 is 4 months old... we had also a 1.8.4 with many bug fixes. And there is already a 1.9.0 which had several fixes.

Update your release. When this still occurs with the actual release add an issue with an reproducable example and some informations needed for reproduction

 

 

Posted by Thomas Weidner (thomas) on 2009-08-29T11:55:02.000+0000

Closing as it's not reproducable with actual release and the given informations.

 

 